/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guilherme.view;

import br.com.guilherme.model.Cartela;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Guilherme Lourenço
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private int numeroDeCartelas;
    private List<Cartela> cartelas;
    private Stack pilhaNumerosSorteio;
    private int qtdeNumSorteados;
    private boolean oneWinner;
    private Stack pilhaNumerosSorteados;
    
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static List<Integer> obterNumerosDaCartela(){
        List<Integer> nums = new ArrayList<>();
        Stack pilha = new Stack();
        for(int i = 0; i < 60; i++){
            pilha.push(i+1);
        }
        for(int i = 0; i< 12; i++){
            Collections.shuffle(pilha);
            int numero = (int) pilha.pop();
            nums.add(numero);
        }
        return nums;
    }
    
    public TelaPrincipal(int numeroDeCartelas){
        this();
        this.numeroDeCartelas = numeroDeCartelas;
        this.setVisible(true);
        this.listaDeCartelas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.pilhaNumerosSorteio = new Stack();
        this.cartelas = new ArrayList<>();
        this.qtdeNumSorteados = 0;
        this.oneWinner = false;
        this.pilhaNumerosSorteados = new Stack();
        
        for(int i = 0; i < 60; i++){
            this.pilhaNumerosSorteio.push(i+1);
        }
        
        for(int i = 0; i < this.numeroDeCartelas; i++){
            Cartela novaCartela = new Cartela(this.obterNumerosDaCartela());
            this.cartelas.add(novaCartela);
        }
       
        this.listaDeCartelas.setListData(cartelas.toArray());
        this.listaDeCartelas.setSelectedIndex(0);
        
        jScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        txtAreaNumSorteados.setLineWrap(true);
        txtAreaNumSorteados.setWrapStyleWord(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeCartelas = new javax.swing.JList();
        btnVisualisarCartela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaNumSorteados = new javax.swing.JTextArea();
        btnSortearProximo = new javax.swing.JButton();
        btnSortearTudo = new javax.swing.JButton();
        lblQtdeNumSorteados = new javax.swing.JLabel();
        cbCartelasVencedoras = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bingo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cartelas"));

        jScrollPane1.setViewportView(listaDeCartelas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        btnVisualisarCartela.setText("Visualisar Cartela Selecionada");
        btnVisualisarCartela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualisarCartelaActionPerformed(evt);
            }
        });

        jLabel1.setText("Cartela Vencedora por ordem: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Numeros Sorteados"));

        txtAreaNumSorteados.setEditable(false);
        txtAreaNumSorteados.setColumns(20);
        txtAreaNumSorteados.setRows(5);
        jScrollPane2.setViewportView(txtAreaNumSorteados);

        btnSortearProximo.setText("Sortear Próximo Numero");
        btnSortearProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearProximoActionPerformed(evt);
            }
        });

        btnSortearTudo.setText("Sortear Rapidamente");
        btnSortearTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearTudoActionPerformed(evt);
            }
        });

        lblQtdeNumSorteados.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lblQtdeNumSorteados.setForeground(new java.awt.Color(0, 255, 51));
        lblQtdeNumSorteados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdeNumSorteados.setText("NM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSortearTudo)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSortearProximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQtdeNumSorteados)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortearProximo)
                    .addComponent(lblQtdeNumSorteados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSortearTudo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisualisarCartela)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCartelasVencedoras, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnVisualisarCartela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbCartelasVencedoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualisarCartelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualisarCartelaActionPerformed
        try{
            Cartela cartelaEscolhida = (Cartela) listaDeCartelas.getSelectedValue();
            TelaCartela novaTelaCartela = new TelaCartela(cartelaEscolhida.getValores(), cartelaEscolhida.getNumCartela(), cartelaEscolhida.getPontos(), this.pilhaNumerosSorteados);
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro, tente novamente!");
        }
    }//GEN-LAST:event_btnVisualisarCartelaActionPerformed

    private void btnSortearProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearProximoActionPerformed
        try{
            if(pilhaNumerosSorteio.size() > 0){
                Collections.shuffle(pilhaNumerosSorteio);
                int numeroSorteado = (int) this.pilhaNumerosSorteio.pop();
                this.pilhaNumerosSorteados.push(numeroSorteado);
                txtAreaNumSorteados.append("["+numeroSorteado+"]" + " ");
                for(Cartela c : cartelas){
                    List<Integer> valores = c.getValores();
                    for (Integer valor : valores) {
                        if(valor == numeroSorteado){
                            c.addPonto();
                        }
                    }
                    
                    if(c.getPontos() == 12 && c.getVenceu()==false){
                        cbCartelasVencedoras.addItem("Cartela " + c.getNumCartela());
                        listaDeCartelas.setSelectedIndex(c.getNumCartela()-1);
                        listaDeCartelas.setSelectionBackground(Color.RED);
                        c.setVenceu(true);
                        if(!oneWinner){
                            JOptionPane.showMessageDialog(null, "VENCEDOR ENCONTRADO!!!");
                            oneWinner=true;
                        }
                    }
                }
                this.qtdeNumSorteados++;
                lblQtdeNumSorteados.setText("Sorteados: " + this.qtdeNumSorteados);
            }else{
                JOptionPane.showMessageDialog(null, "Fim do sorteio, os números acabaram!");
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro, tente novamente!");
        }
    }//GEN-LAST:event_btnSortearProximoActionPerformed

    private void btnSortearTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearTudoActionPerformed
        try{
            for(int i = 0; i < (60 - this.qtdeNumSorteados); i++){
                btnSortearProximo.doClick();
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Não foi possível realizar o sorteio.");
        }
    }//GEN-LAST:event_btnSortearTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortearProximo;
    private javax.swing.JButton btnSortearTudo;
    private javax.swing.JButton btnVisualisarCartela;
    private javax.swing.JComboBox cbCartelasVencedoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQtdeNumSorteados;
    private javax.swing.JList listaDeCartelas;
    private javax.swing.JTextArea txtAreaNumSorteados;
    // End of variables declaration//GEN-END:variables
}
