/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guilherme.view;

import java.awt.Color;
import java.util.List;
import java.util.Stack;
import javax.swing.SwingConstants;

/**
 *
 * @author Guilherme Lourenço
 */
public class TelaCartela extends javax.swing.JFrame {

    /**
     * Creates new form TelaCartela
     */
    
    List<Integer> numeros; 
            
    public TelaCartela() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        txtNum1.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum2.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum3.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum4.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum5.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum6.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum7.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum8.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum9.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum10.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum11.setHorizontalAlignment(SwingConstants.CENTER);
        txtNum12.setHorizontalAlignment(SwingConstants.CENTER);
        this.setVisible(true);
    }
    
    public TelaCartela(List<Integer> nums, int numCartela, int pontos, Stack numerosSorteados){
        this();
        this.numeros = nums;
        lblNumeroDaCartela.setText(String.valueOf(numCartela));
        lblPontos.setText(String.valueOf(pontos));
        txtNum1.setText(String.valueOf(nums.get(0)));
        txtNum2.setText(String.valueOf(nums.get(1)));
        txtNum3.setText(String.valueOf(nums.get(2)));
        txtNum4.setText(String.valueOf(nums.get(3)));
        txtNum5.setText(String.valueOf(nums.get(4)));
        txtNum6.setText(String.valueOf(nums.get(5)));
        txtNum7.setText(String.valueOf(nums.get(6)));
        txtNum8.setText(String.valueOf(nums.get(7)));
        txtNum9.setText(String.valueOf(nums.get(8)));
        txtNum10.setText(String.valueOf(nums.get(9)));
        txtNum11.setText(String.valueOf(nums.get(10)));
        txtNum12.setText(String.valueOf(nums.get(11)));
        for(int i = 0; i < numerosSorteados.size(); i++){
            if(numerosSorteados.get(i)== Integer.valueOf(txtNum1.getText())){
                txtNum1.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum2.getText())){
                txtNum2.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum3.getText())){
                txtNum3.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum4.getText())){
                txtNum4.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum5.getText())){
                txtNum5.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum6.getText())){
                txtNum6.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum7.getText())){
                txtNum7.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum8.getText())){
                txtNum8.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum9.getText())){
                txtNum9.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum10.getText())){
                txtNum10.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum11.getText())){
                txtNum11.setBackground(Color.red);
            }else if(numerosSorteados.get(i) == Integer.valueOf(txtNum12.getText())){
                txtNum12.setBackground(Color.red);
            }
            
        }
        //System.out.println(nums);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNumeroDaCartela = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtNum3 = new javax.swing.JTextField();
        txtNum4 = new javax.swing.JTextField();
        txtNum5 = new javax.swing.JTextField();
        txtNum6 = new javax.swing.JTextField();
        txtNum7 = new javax.swing.JTextField();
        txtNum8 = new javax.swing.JTextField();
        txtNum9 = new javax.swing.JTextField();
        txtNum10 = new javax.swing.JTextField();
        txtNum11 = new javax.swing.JTextField();
        txtNum12 = new javax.swing.JTextField();
        lblPontos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cartela");

        jLabel1.setText("Cartela Nº: ");

        lblNumeroDaCartela.setText("Num");

        txtNum1.setEditable(false);

        txtNum2.setEditable(false);

        txtNum3.setEditable(false);

        txtNum4.setEditable(false);

        txtNum5.setEditable(false);

        txtNum6.setEditable(false);

        txtNum7.setEditable(false);

        txtNum8.setEditable(false);

        txtNum9.setEditable(false);

        txtNum10.setEditable(false);

        txtNum11.setEditable(false);

        txtNum12.setEditable(false);

        lblPontos.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(255, 51, 0));
        lblPontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontos.setText("NM");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PONTOS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumeroDaCartela)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNum4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNum6, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(txtNum3)))
                            .addComponent(lblPontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNum7)
                                    .addComponent(txtNum10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNum11, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                        .addComponent(txtNum8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNum12, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(txtNum9))))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNumeroDaCartela))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPontos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCartela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNumeroDaCartela;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum10;
    private javax.swing.JTextField txtNum11;
    private javax.swing.JTextField txtNum12;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    private javax.swing.JTextField txtNum4;
    private javax.swing.JTextField txtNum5;
    private javax.swing.JTextField txtNum6;
    private javax.swing.JTextField txtNum7;
    private javax.swing.JTextField txtNum8;
    private javax.swing.JTextField txtNum9;
    // End of variables declaration//GEN-END:variables
}
